name: Send notification

on:
  schedule:
    - cron: '8 * * * *'

jobs:
  send-msg:
    runs-on: ubuntu-latest
    steps:
      - name: run
        id: message
        run: |
          echo "##[set-output name=msg;]$(date)"

      # 纯文本格式
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: ${{ steps.message.outputs.msg }}
          mentioned_list: '["@all"]'
